courses/urls.py
from django.urls import path

from . import views

app_name = 'courses'

urlpatterns = [
    path("", views.CourseListView.as_view(), name="course_list"),
    # path("new", views.new, name="course_new"),
    path("new", views.CourseCreateView.as_view(), name="course_new"),
    path("semester/<int:semester>", views.CourseListView.as_view(), name="course_by_semester"),
    path("<slug:slug>", views.CourseDetailView.as_view(), name="course_detail"),
    # path("<slug:slug>", views.detail, name="course_detail"),
    path("<slug:slug>/edit/", views.CourseUpdateView.as_view(), name="course_edit"),
    path('<int:pk>/delete/', views.CourseDeleteView.as_view(), name='course_delete'),
]

tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'

urlpatterns = [
    path("", views.TaskListView.as_view(), name="tasks_list"),
    path("new/", views.TaskCreateView.as_view(), name="task_new"),
    path('<int:task_id>/update_status/', views.update_status, name='update_task_status'),
    path("<int:course_id>/new/", views.TaskCreateView2.as_view(), name="task_new_for_course"),
    path("<str:tasks_id>/", views.TaskDetailView.as_view(), name="tasks_detail"),
    path("<int:pk>/edit/", views.TaskUpdateView.as_view(), name="task_edit"),
    path("status/<str:status>/", views.TaskListView.as_view(), name="tasks_by_status"),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name='task_delete'),
]

zikola/urls.py
from django.contrib import admin
from django.urls import include, path
from zikola import views

urlpatterns = [
    path("", views.index, name="main"),
    path('admin/', admin.site.urls),
    path('courses/', include('courses.urls', namespace="courses")),
    path('tasks/', include('tasks.urls', namespace="tasks")),
]

courses/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

class Course(models.Model):
    name = models.CharField(max_length=200, unique=True)
    semester = models.PositiveIntegerField()
    description = models.TextField(blank=True, null=True)
    slug = models.SlugField(blank=True,unique=True, default='', editable=False)
    sks = models.PositiveIntegerField(default=2)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)
    
    def __str__(self):
        return f"{self.id} - {self.name}"

courses/forms.py
from django import forms
from . import models

class CourseForm(forms.ModelForm):    
    class Meta:
        model = models.Course
        fields = ['name', 'semester', 'description','sks']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4, 'class': 'form-control'}),
            'name': forms.TextInput(attrs={
                                           'class': 'form-control',
                                           'placeholder': 'Basis Data'}),
            'semester': forms.NumberInput(attrs={'class': 'form-control',
                                                  'placeholder': '1',
                                                  'min':1,
                                                  'max':8}),
            'sks': forms.NumberInput(attrs={'class': 'form-control',
                                                  'placeholder': '2',
                                                  'min':1,
                                                  'max':8}),
        }

courses/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from . import models
from . import forms
from django.views.generic import ListView, DetailView,DeleteView

def detail(request, slug):
    course = models.Course.objects.get(slug=slug)
    print(course)
    context = {
        'Title': course.name,
        'Content': course.description,
        'Course': course,
        'Slug': slug
    }
    return render(request, 'courses/detail.html', context)

def semester(request, semester):
    courses = models.Course.objects.filter(semester=semester)
    context = {
        'Title': 'Home',
        'Content': 'Matakuliah Semester ' + str(semester),
        'Courses': courses,
        'range' : range(1,8),
        'selected_semester' : semester
        
    }
    return render(request, 'courses/index.html', context)

def new(request):
    if request.method == 'POST':
        form = forms.CourseForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse({'message': 'Course successfully created!'}, status=200)
        else:
            return JsonResponse({'error': 'Form submission failed.'}, status=400)
    else:
        form = forms.CourseForm()
    context = {
        'course_form': form,
    }
    
    return render(request, 'courses/new.html', context)

class CourseListView(ListView):
    model = models.Course
    context = {
        'Title': 'Home',
        'Content': 'Welcome to the homepage',
        'range' : range(1,8),
        
    }
    template_name = 'courses/index.html'
    
    context_object_name = 'Courses'
    
    def get_queryset(self):
        semester =self.kwargs.get('semester', None)
        if semester:
            return models.Course.objects.filter(semester=semester)
        return models.Course.objects.order_by('semester')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Title'] = 'Home' 
        context['Content'] = 'Welcome to the homepage' 
        context['range'] = range(1, 8) 
        context['selected_semester'] = self.kwargs.get('semester', None)
        return context
    
class CourseCreateView(CreateView):
    model = models.Course
    form_class = forms.CourseForm
    template_name = 'courses/new.html'
    success_url = reverse_lazy('courses:course_list')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['course_form'] = context.pop('form')
        return context

    def form_valid(self, form):
        self.object = form.save()
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            return JsonResponse({'message': 'Course successfully created!'}, status=200)
        return super().form_valid(form)

    def form_invalid(self, form):
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
             return JsonResponse({'error': 'Form submission failed.', 'errors': form.errors}, status=400)
        return super().form_invalid(form)
    
class CourseDetailView(DetailView):
    model = models.Course
    template_name = 'courses/detail.html'
    slug_field = 'slug'       
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course = self.get_object()

        context['Course'] = course
        context['Slug'] = course.slug
        context['Tasks'] = course.tasks.all()
        return context

from django.views.generic.edit import UpdateView

class CourseUpdateView(UpdateView):
    model = models.Course
    form_class = forms.CourseForm
    template_name = 'courses/edit.html'
    success_url = reverse_lazy('courses:course_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = context.pop('form')
        return context
    
class CourseDeleteView(DeleteView):
    model = models.Course
    success_url = reverse_lazy('courses:course_list')

    def delete(self, request, *args, **kwargs):
        task = self.get_object()
        task.delete()
        return JsonResponse({'status': 'success', 'message': 'Course successfully deleted'})

courses/templates/courses/ajax.html
<script>
    // Insert Data
    $("#btnsave").click(function (){
        //console.log("Save button clicked");
        let output = ""; // Initialize output variable

        let student_id = $("#stuid").val();
        let name = $("#nameid").val();
        let email = $("#emailid").val();
        let password = $("#passwordid").val();
        let csrf = $("input[name=csrfmiddlewaretoken]").val();

        if (name == ""){
            console.log("please enter name");
        } else if (email == ""){
            console.log("please enter email");
        } else if (password == ""){
            console.log("please enter password");
        } else {
            //console.log('name: ', name);
            //console.log('email: ', email);
            //console.log('password: ', password);
            let mydata = {
                student_id: student_id,
                name: name, 
                email: email, 
                password: password, 
                csrfmiddlewaretoken: csrf
            }
            {% comment %} $.ajax({
                url: "{% url 'save' %}",
                method: "POST",
                data: mydata,
                success: function (data){
                    console.log('data: ', data);
                    console.log('data.status: ', data.status);
                    let x = data.student_data;
                    if (data.status == "Save"){
                        $("#msg").text("Form Submitted Successfuly");
                        $("#msg").show();
                        //console.log("Form Submitted Successfully");
                        //console.log('data.student_data: ', x);

                        for (let i = 0; i < x.length; i++) {
                            output += "<tr><td>" + x[i].id + "</td><td>" + x[i].name + "</td><td>" + x[i].email + "</td><td>" + x[i].password + "</td><td> <input type='button' class='btn btn-warning btn-sm btn-edit' value='Edit' data-sid='" + x[i].id + "'/> <input type='button' class='btn btn-danger btn-sm btn-del' value='Delete' data-sid='" + x[i].id + "'/></td></tr>";
                        }
                        $("#tbody").html(output);
                        $("#stuid").val("");
                        // Reset form after adding a student
                        $("form")[0].reset();
                    }
                    if (data.status == 0){
                        //console.log("Unable To Save Form");
                        $("#msg").text("Unable To Save Form");
                        $("#msg").show();

                        // Set student id empty
                        $("#stuid").val("");
                        $("form")[0].reset();
                    }
                },
            }); {% endcomment %}
        }
    });

    // Delete data
    {% comment %} $("tbody").on("click", ".btn-del", function (){
        console.log("Delete button clicked");
        let id = $(this).attr("data-sid");
        let csrf = $("input[name=csrfmiddlewaretoken]").val();
        console.log("id: ", id);
        mydata = { student_id: id, csrfmiddlewaretoken: csrf };
        mythis = this;

        $.ajax({
            url: "{% url 'delete' %}",
            method: "POST",
            data: mydata,
            success: function (data){
                console.log('data: ', data);
                if (data.status == 1){
                    //console.log('Data deleted successfully');
                    $("#msg").text("Data deleted successfully");
                    $("#msg").show();

                    // Fade out deleted row
                    $(mythis).closest("tr").fadeOut();
                }
                if (data.status == 0){
                    //console.log('Unable to delete data');
                    $("#msg").text("Unable to delete data");
                    $("#msg").show();
                }
            },
        });
    }); {% endcomment %}

    // Edit data
    $("tbody").on("click", ".btn-edit", function (){
        console.log("Edit button clicked");
        let id = $(this).attr("data-sid");
        let csrf = $("input[name=csrfmiddlewaretoken]").val();
        console.log("id: ", id);
        mydata = { student_id: id, csrfmiddlewaretoken: csrf };

        $.ajax({
            url: "{% url 'edit' %}",
            method: "POST",
            data: mydata,
            success: function (data){
                console.log("data: ", data);
                // Insert student data to form field
                $("#stuid").val(data.id);
                $("#nameid").val(data.name);
                $("#emailid").val(data.email);
                $("#passwordid").val(data.password);
            },
        });
    });

</script>

courses/templates/courses/confirm_delete.html
_<script>
    document.addEventListener('DOMContentLoaded', function () {
      var deleteModal = new bootstrap.Modal(document.getElementById('deleteModal'));
      var confirmDeleteBtn = document.getElementById('confirmDeleteBtn');
      var courseId = null;

      // Handle course delete button click to set course id
      document.querySelectorAll('.btn-del').forEach(function (btn) {
        btn.addEventListener('click', function () {
          courseId = this.getAttribute('data-course-id');
        });
      });

      // Handle the actual deletion when confirm is clicked
      confirmDeleteBtn.addEventListener('click', function () {
        if (courseId) {
          // Make AJAX request to delete the course
          fetch(`/courses/${courseId}/delete/`, {
            method: 'POST',
            headers: {
              'X-CSRFToken': '{{ csrf_token }}',
            },
          })
            .then(function (response) {
              if (response.ok) {
                location.reload(); // Reload page after successful delete
              } else {
                alert('Failed to delete course');
              }
            })
            .catch(function () {
              alert('An error occurred');
            });
        }
        deleteModal.hide(); // Close the modal
      });
    });
  </script>

courses/templates/courses/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <title>{{Course.name}}</title>
  </head>
  <body>
    <div class="container mt-5">
      <h2 class="text-center alert alert-info">Tugas Final Web {{Slug}}</h2>

      
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item"><a href="/courses">Courses</a></li>
          <li class="breadcrumb-item active" aria-current="page">{{Course.name}}</li>
        </ol>
      </nav>
      
      <div class="d-flex justify-content-end">
          <a href="{% url 'tasks:task_new_for_course' Course.id %}" class="btn btn-primary mb-3">
            <i class="bi bi-plus"></i>Create Task
          </a>
      </div>

      <main>
        <p>Nama : {{Course.name}}</p>
        <p>SKS :{{Course.sks}}</p>
        <p>Semester : {{Course.semester}}</p>
        <p>Deskripsi : {{Course.description}}</p>
        <h4>Tasks</h4>
        {% if Tasks %}
        <ul>
            {% for task in Tasks %}
                <li>
                  <a href="{% url 'tasks:tasks_detail' tasks_id=task.id %}">
                    <strong>{{ task.title }}</strong>  (Due: {{ task.due_date }})
                  </a>
                </li>
            {% endfor %}
        </ul>
      {% else %}
        <p>No tasks assigned to this course.</p>
      {% endif %}
      
      </main>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>

    {% comment %} {% include "courses/ajax.html" %} {% endcomment %}
  </body>
</html>

courses/templates/courses/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Edit Course</title>
</head>
<body>
    <div class="container mt-5">
        <h2 class="text-center alert alert-warning">Edit Course</h2>

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'courses:course_list' %}">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Edit</li>
            </ol>
        </nav>

        <div class="card p-4 shadow-sm">
            <form method="post">
                {% csrf_token %}
                {% for field in form %}
                <div class="mb-3">
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                    <div class="text-danger">
                        {{ field.errors }}
                    </div>
                    {% endif %}
                </div>
                {% endfor %}
                <button type="submit" class="btn btn-success w-100">Update Course</button>
            </form>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

courses/templates/courses/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <title>Zikola</title>
  </head>
  <body>
    <div class="container mt-5">
      <h2 class="text-center alert alert-info">Tugas Final Web</h2>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item active" aria-current="page">
            <a href="{% url "courses:course_list"%}">Courses</a>
          </li>
        </ol>
      </nav>
      <div class="semester-filter mb-4">
        <div class="d-flex gap-2">
        {%if selected_semester%}
          <a href="{% url "courses:course_list"%}" class="badge bg-danger text-decoration-none">Remove Filter</a>
        {%endif%}
        {% for semester in range %}
            {% if selected_semester == semester %}
                <a href="{% url "courses:course_by_semester" semester=semester %}" class="badge bg-primary text-decoration-none">Semester {{ semester }}</a>
            {% else %}
                <a  href="{% url "courses:course_by_semester" semester=semester %}" class="badge bg-secondary text-decoration-none">Semester {{ semester }}</a>
            {% endif %}
        {% endfor %}
        </div>
      </div>  

    <div class="d-flex justify-content-end">
      <a href="{% url "courses:course_new"%}" class="btn btn-primary mb-3"><i class="bi bi-plus"></i>New Course</a>  
    </div>
    
    <div class="row">
        <div>
          <table class="table table-hover table-striped">
            <thead>
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Semester</th>
                <th>SKS</th>
                <th>Tugas</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody id="tbody">
              {% for course in Courses %}
              <tr>
                <td>{{course.id}}</td>
                <td>
                  <a href="{% url "courses:course_detail" slug=course.slug %}">{{course.name}}</a>
                </td>
                <td>{{course.semester}}</td>
                <td>{{course.sks}}</td>
                <td>{{course.tasks.count}}</td>
                <td>
                  <a href="{% url 'courses:course_edit' slug=course.slug %}" 
                  class="btn btn-warning btn-sm">Edit</a>
                  <button
                    type="button"
                    class="btn btn-danger btn-sm btn-del"
                    data-bs-toggle="modal"
                    data-bs-target="#deleteModal"
                    data-course-id="{{ course.id }}">
                    Delete
                  </button>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Confirm Deletion</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            Are you sure you want to delete this course?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            <button type="button" class="btn btn-danger" id="confirmDeleteBtn">Delete</button>
          </div>
        </div>
      </div>
    </div>


    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
    {% include "courses/confirm_delete.html" %}
    {% comment %} {% include "courses/ajax.html" %} {% endcomment %}
  </body>
</html>

courses/templates/courses/new.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <title>New Course</title>
  </head>
  <body>
    <div class="container mt-5">
      <h2 class="text-center alert alert-info">Tugas Final Web</h2>

      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="/">Home</a></li>
          <li class="breadcrumb-item"><a href="{% url "courses:course_list"%}">Courses</a></li>
          <li class="breadcrumb-item active" aria-current="page">New</li>
        </ol>
      </nav>

      <main>
        <div id="alert-container" class="mt-3"></div>
        <form id="course-form" method="post" class="card p-4 shadow-sm">
          {% csrf_token %} {% for form in course_form %}
          <div class="form-group">
            <div class="form-row mb-3">
              <div class="col">{{form.label}} {{form}}</div>
              <div id="{{form.name}}-error" class="text-danger"></div>
            </div>
          </div>
          {% endfor %}
          <button type="submit" class="btn btn-primary w-100">Submit</button>
        </form>
      </main>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script>
      $(document).ready(function () {
        $("#course-form").submit(function (event) {
          event.preventDefault();

          var formData = $(this).serialize();
          $("#response").hide();

          $.ajax({
            url: "{% url "courses:course_new" %}",
            type: "POST",
            data: formData,
            success: function (response) {
              $("#course-form")[0].reset();
              const alertHtml = `
              <div class="alert alert-success alert-dismissible fade show" role="alert">
                Course successfully submitted!.
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>`;
            $("#alert-container").html(alertHtml);

            setTimeout(function () {
              $(".alert").alert('close');
            }, 3000);
            },
            error: function (xhr, errmsg, err) {
              var response = JSON.parse(xhr.responseText);
              $("#response").addClass("alert-danger").text("Course Failed submitted!").show();
              $.each(response.errors, function(field, messages) {
                var errorMessage = messages.join(", ");
                $("#" + field + "-error").text(errorMessage);
              });
            }

          });
        });
      });
    </script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>